packages:
  - packages/*

catalog:
  '@cloudflare/vite-plugin': 1.23.1
  '@cloudflare/workers-types': 4.20260207.0
  '@kubb/cli': 4.22.3
  '@kubb/core': 4.22.3
  '@kubb/plugin-client': 4.22.3
  '@kubb/plugin-oas': 4.22.3
  '@kubb/plugin-ts': 4.22.3
  '@kubb/react-fabric': 0.12.11
  '@panva/hkdf': 1.2.1
  '@stricli/auto-complete': 1.2.5
  '@stricli/core': 1.2.5
  '@tailwindcss/vite': 4.1.18
  '@tmcw/togeojson': 7.1.2
  '@turf/area': 7.3.4
  '@turf/boolean-point-in-polygon': 7.3.4
  '@turf/center': 7.3.4
  '@turf/envelope': 7.3.4
  '@turf/helpers': 7.3.4
  '@turf/intersect': 7.3.4
  '@types/geojson': 7946.0.16
  '@types/node': 24.10.12
  '@types/react': 19.2.13
  '@types/react-dom': 19.2.3
  '@xmldom/xmldom': 0.9.8
  better-auth: 1.4.18
  capnweb: 0.4.0
  cookie: 1.1.1
  geojson: 0.5.0
  jose: 6.1.3
  kysely: ^0.28.11
  kysely-postgres-js: ^3.0.0
  lefthook: 2.1.1
  postgres: 3.4.8
  prettier: 3.8.1
  react: 19.2.4
  react-dom: 19.2.4
  react-server-dom-webpack: 19.2.4
  rwsdk: 1.0.0-beta.53
  tailwindcss: 4.1.18
  tiny-invariant: 1.3.3
  ts-pattern: 5.9.0
  typescript: 5.9.3
  vite: 7.3.1
  wrangler: 4.65.0
  zod: 4.3.6

catalogMode: strict
