packages:
  - 'packages/*'
catalogMode: strict
catalog:
  '@kubb/cli': '3.18.0'
  '@kubb/core': '3.18.0'
  '@kubb/plugin-client': '3.18.0'
  '@kubb/plugin-oas': '3.18.0'
  '@kubb/plugin-ts': '3.18.0'
  '@mui/material': '7.3.1'
  '@panva/hkdf': '1.2.1'
  '@stricli/auto-complete': '^1.1.2'
  '@stricli/core': '^1.1.2'
  '@tailwindcss/vite': '4.1.10'
  '@tmcw/togeojson': '7.1.2'
  '@turf/area': '7.2.0'
  '@turf/boolean-point-in-polygon': '7.2.0'
  '@turf/center': '7.2.0'
  '@turf/envelope': '7.2.0'
  '@turf/helpers': '7.2.0'
  '@turf/intersect': '7.2.0'
  '@types/bun': '1.2.20'
  '@types/geojson': '7946.0.16'
  '@types/node': '24.3.0'
  '@types/react': '19.1.10'
  '@types/react-dom': '19.1.7'
  '@xmldom/xmldom': '0.9.8'
  cookie: '1.0.2'
  geojson: '0.5.0'
  jose: '6.0.12'
  lefthook: '^1.12.2'
  postgres: '3.4.7'
  rwsdk: '0.1.35'
  tailwindcss: '4.1.10'
  tiny-invariant: '1.3.3'
  ts-pattern: '5.8.0'
  typescript: '5.9.2'
  vite: '6.2.6'
  wrangler: '4.30.0'
  zod: '3.25.76'
