// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.FieldUsage */
type FieldUsage = 
  | 'TOP_HALF'
  | 'BOTTOM_HALF'
  | 'FULL_FIELD';

export default FieldUsage;
