// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface jsonb_array_avg_params {
  arr: unknown;
}

/** Return type for jsonb_array_avg */
export type jsonb_array_avg_return_type = number;
