// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface jsonb_array_max_params {
  arr: unknown;
}

/** Return type for jsonb_array_max */
export type jsonb_array_max_return_type = number;
