// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PostId } from './Post';

/** Represents the view public.metabase_post_location */
export default interface MetabasePostLocation {
  id: PostId;

  startTime: Date | null;

  longitude: number;

  latitude: number;
}
