// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.PostStatus */
type PostStatus = 
  | 'ERROR'
  | 'COMPLETED'
  | 'PROCESSING'
  | 'INIT';

export default PostStatus;
