// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as PostType } from './PostType'
import { FeatureCollection, LineString } from 'geojson'
import type { UserId } from './User'
import type { FieldId } from './Field'
import type { default as PostStatus } from './PostStatus'

/** Identifier type for public.Post */
export type PostId = number & { __brand: 'public.Post' }

/** Represents the table public.Post */
export default interface Post {
  id: PostId

  createdAt: Date

  updatedAt: Date

  type: PostType

  text: string

  key: string

  geoJson: FeatureCollection<LineString> | null

  totalDistance: number

  elapsedTime: number

  totalSprintTime: number

  maxSpeed: number

  averageSpeed: number

  userId: UserId

  sprints: Array<FeatureCollection<LineString>>

  runs: Array<FeatureCollection<LineString>>

  startTime: Date | null

  fieldId: FieldId | null

  image: string | null

  halfTime: number

  status: PostStatus

  statusInfo: string
}

/** Represents the initializer for the table public.Post */
export interface PostInitializer {
  /** Default value: nextval('"Post_id_seq"'::regclass) */
  id?: PostId

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date

  updatedAt: Date

  type: PostType

  text: string

  key: string

  geoJson?: FeatureCollection<LineString> | null

  /** Default value: 0 */
  totalDistance?: number

  /** Default value: 0 */
  elapsedTime?: number

  /** Default value: 0 */
  totalSprintTime?: number

  /** Default value: 0 */
  maxSpeed?: number

  /** Default value: 0 */
  averageSpeed?: number

  userId: UserId

  sprints?: FeatureCollection<LineString> | null

  runs?: FeatureCollection<LineString> | null

  startTime?: Date | null

  fieldId?: FieldId | null

  image?: string | null

  /** Default value: '-1'::integer */
  halfTime?: number

  /** Default value: 'INIT'::"PostStatus" */
  status?: PostStatus

  /** Default value: ''::text */
  statusInfo?: string
}

/** Represents the mutator for the table public.Post */
export interface PostMutator {
  id?: PostId

  createdAt?: Date

  updatedAt?: Date

  type?: PostType

  text?: string

  key?: string

  geoJson?: FeatureCollection<LineString> | null

  totalDistance?: number

  elapsedTime?: number

  totalSprintTime?: number

  maxSpeed?: number

  averageSpeed?: number

  userId?: UserId

  sprints?: FeatureCollection<LineString> | null

  runs?: FeatureCollection<LineString> | null

  startTime?: Date | null

  fieldId?: FieldId | null

  image?: string | null

  halfTime?: number

  status?: PostStatus

  statusInfo?: string
}
