// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as Platform } from './Platform';
import type { UserId } from './User';

/** Identifier type for public.SocialLogin */
export type SocialLoginId = number & { __brand: 'public.SocialLogin' };

/** Represents the table public.SocialLogin */
export default interface SocialLogin {
  id: SocialLoginId;

  createdAt: Date;

  updatedAt: Date;

  platform: Platform;

  platformId: string;

  platformMeta: string;

  accessToken: string;

  refreshToken: string;

  userId: UserId;

  expiresAt: Date;

  platformScope: string;
}

/** Represents the initializer for the table public.SocialLogin */
export interface SocialLoginInitializer {
  /** Default value: nextval('"SocialLogin_id_seq"'::regclass) */
  id?: SocialLoginId;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;

  platform: Platform;

  platformId: string;

  platformMeta: string;

  accessToken: string;

  refreshToken: string;

  userId: UserId;

  /** Default value: NULL::timestamp without time zone */
  expiresAt?: Date;

  platformScope: string;
}

/** Represents the mutator for the table public.SocialLogin */
export interface SocialLoginMutator {
  id?: SocialLoginId;

  createdAt?: Date;

  updatedAt?: Date;

  platform?: Platform;

  platformId?: string;

  platformMeta?: string;

  accessToken?: string;

  refreshToken?: string;

  userId?: UserId;

  expiresAt?: Date;

  platformScope?: string;
}
