// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as StravaWebhookEventStatus } from './StravaWebhookEventStatus';

/** Identifier type for public.StravaWebhookEvent */
export type StravaWebhookEventId = number & { __brand: 'public.StravaWebhookEvent' };

/** Represents the table public.StravaWebhookEvent */
export default interface StravaWebhookEvent {
  id: StravaWebhookEventId;

  createdAt: Date;

  updatedAt: Date;

  status: StravaWebhookEventStatus;

  body: string;

  errors: string[] | null;
}

/** Represents the initializer for the table public.StravaWebhookEvent */
export interface StravaWebhookEventInitializer {
  /** Default value: nextval('"StravaWebhookEvent_id_seq"'::regclass) */
  id?: StravaWebhookEventId;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;

  status: StravaWebhookEventStatus;

  body: string;

  errors?: string[] | null;
}

/** Represents the mutator for the table public.StravaWebhookEvent */
export interface StravaWebhookEventMutator {
  id?: StravaWebhookEventId;

  createdAt?: Date;

  updatedAt?: Date;

  status?: StravaWebhookEventStatus;

  body?: string;

  errors?: string[] | null;
}
