// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.StravaWebhookEventStatus */
type StravaWebhookEventStatus = 
  | 'PENDING'
  | 'ERRORED'
  | 'COMPLETED';

export default StravaWebhookEventStatus;
