// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as UserType } from './UserType';

/** Identifier type for public.User */
export type UserId = number & { __brand: 'public.User' };

/** Represents the table public.User */
export default interface User {
  id: UserId;

  createdAt: Date;

  updatedAt: Date;

  email: string | null;

  firstName: string | null;

  lastName: string | null;

  locale: string;

  picture: string | null;

  auth0Sub: string | null;

  emailVerified: boolean;

  type: UserType;
}

/** Represents the initializer for the table public.User */
export interface UserInitializer {
  /** Default value: nextval('"User_id_seq"'::regclass) */
  id?: UserId;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;

  email?: string | null;

  firstName?: string | null;

  lastName?: string | null;

  /** Default value: 'en'::text */
  locale?: string;

  picture?: string | null;

  auth0Sub?: string | null;

  /** Default value: false */
  emailVerified?: boolean;

  /** Default value: 'USER'::"UserType" */
  type?: UserType;
}

/** Represents the mutator for the table public.User */
export interface UserMutator {
  id?: UserId;

  createdAt?: Date;

  updatedAt?: Date;

  email?: string | null;

  firstName?: string | null;

  lastName?: string | null;

  locale?: string;

  picture?: string | null;

  auth0Sub?: string | null;

  emailVerified?: boolean;

  type?: UserType;
}
