service: trackfootball
image: <%= ENV['KAMAL_REGISTRY_USERNAME'] %>/trackfootball
servers:
  web:
    hosts:
      - <%= ENV['HOST_IP'] %>
    options:
      "add-host": host.docker.internal:host-gateway
    labels:
      traefik.http.routers.trackfootball-web.rule: Host(`trackfootball.app`) && PathPrefix(`/`)

env:
  secret:
    - NODE_ENV
    - NEXT_TELEMETRY_DISABLED
    - COOKIE_DOMAIN
    - BACKEND_API
    - MAPBOX_API_TOKEN
    - DATABASE_URL
    - STRAVA_CLIENT_ID
    - STRAVA_CLIENT_SECRET
    - HOMEPAGE_URL
    - AUTH0_SECRET
    - AUTH0_BASE_URL
    - AUTH0_ISSUER_BASE_URL
    - AUTH0_CLIENT_ID
    - AUTH0_CLIENT_SECRET
    - DISCORD_TRACKFOOTBALL_APPLICATION_EVENTS_WEBHOOK
    - STRAVA_WEBHOOK_VERIFY_TOKEN

builder:
  arch: amd64
  cache:
    type: gha

registry:
  username: 
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: <%= ENV['SSH_USER'] %>
  port: <%= ENV['SSH_PORT'] %>


proxy:
  hosts:
    - "trackfootball.app"
  app_port: 6060
  ssl: false
  forward_headers: true
  response_timeout: 60
  healthcheck:
    interval: 5
    path: /api/healthcheck
    timeout: 5

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD