-- CreateEnum
CREATE TYPE "PostStatus" AS ENUM ('INIT', 'PROCESSING', 'COMPLETED', 'ERROR');

-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "status" "PostStatus" NOT NULL DEFAULT E'INIT',
ADD COLUMN     "statusInfo" TEXT NOT NULL DEFAULT E'',
ALTER COLUMN "geoJson" DROP NOT NULL,
ALTER COLUMN "totalDistance" SET DEFAULT 0,
ALTER COLUMN "elapsedTime" SET DEFAULT 0,
ALTER COLUMN "movingTime" SET DEFAULT 0,
ALTER COLUMN "totalSprintTime" SET DEFAULT 0,
ALTER COLUMN "maxSpeed" SET DEFAULT 0,
ALTER COLUMN "averageSpeed" SET DEFAULT 0,
ALTER COLUMN "sprints" DROP NOT NULL,
ALTER COLUMN "runs" DROP NOT NULL,
ALTER COLUMN "startTime" DROP NOT NULL;

-- Initialize data, mark all existing posts as "COMPLETED"
UPDATE "Post" SET "status" = 'COMPLETED';