name: Xata clone (daily, on-demand)

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

env:
  FORCE_COLOR: 3
  XATA_API_KEY: ${{ secrets.XATA_API_KEY }}
  XATA_ORGANIZATIONID: xata
  XATA_PROJECTID: prj_9lg00njeo55nh9ep4nfd4gnmck
  XATA_BRANCHID: gk22igetg11bb046kpjlp1nddg
  XATA_BRANCHNAME: main
  XATA_DATABASENAME: app
  XATA_CLI_SOURCE_POSTGRES_URL: ${{ secrets.XATA_CLI_SOURCE_POSTGRES_URL }}
  PGSTREAM_POSTGRES_SNAPSHOT_ROLE: postgres
  PGSTREAM_POSTGRES_SNAPSHOT_BATCH_BYTES: 83886
  PGSTREAM_POSTGRES_WRITER_BATCH_SIZE: 50
  PGSTREAM_POSTGRES_WRITER_BATCH_TIMEOUT: 1s
  PGSTREAM_POSTGRES_SNAPSHOT_TABLES: public.*

jobs:
  clone:
    name: Xata Clone
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install Xata CLI
        run: |
          curl -fsSL https://xata.io/install.sh | bash
          echo "/home/runner/.config/xata/bin" >> $GITHUB_PATH

      - name: Check Xata status
        run: |
          xata status
          xata version
          xata branch describe

      - name: Xata clone
        run: |
          xata clone start --source-url ${{ env.XATA_CLI_SOURCE_POSTGRES_URL }}
