name: Migrate Database and Deploy
# This workflow is triggered on pushes to the repository.
on:
  push:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

env:
  NO_COLOR: true
  CI: 1
  NEXT_TELEMETRY_DISABLED: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 30
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: false

      - name: Install dependencies
        run: |
          gem install kamal -v 2.6.1

      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx for cache
        uses: docker/setup-buildx-action@v3

      - name: Expose GitHub Runtime for cache
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Write ENV
        run: |
          echo "${{ secrets.ENV_BASE64 }}" | base64 -d > .env

      - name: Dotenv Action
        uses: falti/dotenv-action@v1.1.4

      - name: Write .kamal/secrets
        run: |
          mkdir -p .kamal
          echo "${{ secrets.ENV_BASE64 }}" | base64 -d > .kamal/secrets
      - name: SSH Keyscan
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ env.SSH_PORT }} ${{ env.HOST_IP }} >> ~/.ssh/known_hosts

      - name: SSH Run Command
        run: |
          ssh -p ${{ env.SSH_PORT }} ${{ env.SSH_USER }}@${{ env.HOST_IP }} "ls"

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Kamal Deploy
        run: |
          dotenv kamal deploy
